import type { Metadata } from "next";
import { Forum } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

// const geistSans = Geist({
//     variable: "--font-geist-sans",
//     subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//     variable: "--font-geist-mono",
//     subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const forum = Forum({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--font-forum",
});

// const dancingScript = Dancing_Script({
//     variable: "--font-dancing-script",
//     subsets: ["latin"],
// });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${forum.variable} antialiased font-forum bg-white bg-[url('/assets/background/5.png')]`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
